# Generated by Django 2.0.5 on 2019-01-29 15:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('phase', '0002_auto_20190129_2108'),
    ]

    operations = [
        migrations.AddField(
            model_name='phasesubcategory',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='phase.PhaseCategory'),
        ),
    ]
