# Generated by Django 2.0.5 on 2019-01-30 15:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('phase', '0003_phasesubcategory_category'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='phasecategory',
            options={'ordering': ['id']},
        ),
        migrations.AlterModelOptions(
            name='phasesubcategory',
            options={'ordering': ['id']},
        ),
    ]
